name: Packer-Build

on:
  pull_request:
    types: 
      - closed
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit SHA to run the workflow on'
        required: false
        default: ''

jobs:
  integration-test:
        if: ${{ github.event.pull_request.merged || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        steps:
          - name: Update Ubuntu
            run: sudo apt update
  
          - uses: actions/checkout@v2
            with:
              ref: ${{ github.event.inputs.commit_id }}

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
              node-version: ${{ matrix.node.version }}

          - name: Install PostgresSQL
            run: sudo apt install -y postgresql-14 postgresql-client-14
        
          - name: Enable postgresql service
            run: sudo systemctl enable postgresql

          - name: Start PostgreSQL database
            run: sudo systemctl start postgresql
          
          - name: Create a service account (postgres user)
            run: |
              sudo -u postgres psql -c "CREATE USER ${{ secrets.PG_USER }} WITH PASSWORD '${{ secrets.PG_PASSWORD }}';"
              sudo -u postgres psql -c "ALTER USER ${{ secrets.PG_USER }} CREATEDB;"
        
          
          - name: Create the .env file and write the environment variables to it
            run: |
              cat << EOF > .env
              PG_USER=${{ secrets.PG_USER }}
              PG_PASSWORD=${{ secrets.PG_PASSWORD }}
              PG_DB=${{ secrets.PG_DB }}
              PG_HOST=${{ secrets.PG_HOST }}
              EOF
              echo ".env file created with the specified content."
              
          - name: Install node dependencies
            run: npm install
              
          - name: Run Integration tests
            run: npm test
  

  packer-build:
        needs: integration-test
        runs-on: ubuntu-latest
        steps:
        - name: Update Ubuntu
          run: sudo apt update

        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.inputs.commit_id }}

        - name: Setup packer
          uses: hashicorp/setup-packer@main

        - name: 'Google Auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
    
        - name: 'Use gcloud CLI'
          run: 'gcloud info'
        
        - name: Zip All Content
          run: |
            zip -r build.zip .

        - name: Run packer init
          run: "packer init ./packer/appBuildImage.pkr.hcl"
        
        - name: Run packer build
          run: packer build -var-file=packer/variables.pkrvars.hcl packer/
        
        
