name: Packer-Build

on:
  pull_request:
    types:
      - closed

jobs:
  packer-build:
        runs-on: ubuntu-latest
        steps:
        - name: Update Ubuntu
          run: sudo apt update

        - uses: actions/checkout@v2

        - name: Setup packer
          uses: hashicorp/setup-packer@main

        - name: 'Google Auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
    
        - name: 'Use gcloud CLI'
          run: 'gcloud info'
        
        - name: Zip All Content
          run: |
            zip -r build.zip .

        - name: Run packer init
          run: "packer init ./packer/appBuildImage.pkr.hcl"
        
        - name: Run packer build
          run: |
            packer build \
              -var-file=packer/variables.pkrvars.hcl \ 
              -var "PG_USER=${{ secrets.PG_USER }}" \
              -var "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" \
              -var "PG_DB=${{ secrets.PG_DB }}" \
              -var "PG_HOST=${{ secrets.PG_HOST }}" \
              packer/
        
        
